### ISSUE TITLE
Error in regular expression

### ISSUE THREAD

**Issue by CharliePoole** [PawelTroka/Computator.NET#131]
I was looking at some of your code to figure out how to work around the bug where msbuild can't be found in Linux and discovered that this line has an issue:

https://github.com/PawelTroka/Computator.NET/blob/8052050e5aa6d66cef0d139805d9f48a71637eed/build.cake#L35

When the Mono display name returned the following on Travis...

```
4.6.2 (Stable 4.6.2.16/ac9e222 Tue Jan  3 11:48:26 UTC 2017)
```

...the regex matched the fragment 6.2.16 and the build tried to use MsBuild. I'm going to try anchoring the match to the start of the string for my application.

**Comment by PawelTroka** [comment]
Thanks for this one @CharliePoole
