### ISSUE TITLE
Move away from fat resx WinForms designer based localization architecture (resx files containing everything - like positions and margins is simply a design flaw)

### ISSUE THREAD

**Issue by PawelTroka** [PawelTroka/Computator.NET#89]
We should move away from using so huge resx files as we do now. Instead we should define each form as a language independent form and use separate resx files for strings (containing strings only).

The reasons, besides simpler maintenance are quite clear - huge resx files are slow and error prone. For example see resx files related bugs we have encountered in Mono:

- https://bugzilla.xamarin.com/show_bug.cgi?id=57192
- https://travis-ci.org/PawelTroka/Computator.NET/jobs/244340156

**Comment by PawelTroka** [comment]
For now we can that this is done.
Some small touches needs o be implemented like dealing with EditChartMenus.resx but that part is already planned to be removed in later releases of Computator.NET.

**Comment by sylveon** [comment]
@PawelTroka How was this done? Did you use any automated tool or you manually did it?

**Comment by PawelTroka** [comment]
@sylveon Unfortunately it was mainly manual labour.
1. Copying over *.resx files from Form to other location (easy)
2. Settings Form `Localizable` property to `false` (easy)
3. Setting up Form labels and stuff based on *.resx resource (can be a lot of work)
4. Clearing up *.resx files so they only contain strings (quite easy)
